### ISSUE TITLE
Request to Access Pretrained Weights for SRFlow Model

### ISSUE THREAD

**Issue by AmirMohamadBabaee** [yhjo09/SRFlow-DA#4]
Hello,
Thanks for sharing your great job.

Unfortunately, I've run into an issue that I'm hoping you can help me with. The original SRFlow repository that shared the pre-trained weights for this model appears to have gone down, and the pre-trained weights are no longer accessible. This is problematic for me as I was hoping to leverage the SRFlow model for my own AI projects and research. 

Would you happen to have access to or a local copy of the pre-trained weights from the original SRFlow model? If so, would it be possible for you to share those weights with me? I would be incredibly grateful for the assistance, as it would allow me to continue my work without having to retrain the model from scratch. Please let me know if you are able to help in any way. I'm happy to provide any additional information or context that might be useful. Thank you in advance for your consideration, and I look forward to hearing back from you.

**Comment by yhjo09** [comment]
Dear,
Here is the new link for the pretrained models.
https://onedrive.live.com/?authkey=%21ANhMkst7g0f2g%5FE&id=ADFCB6E1F3CE1167%2130210&cid=ADFCB6E1F3CE1167
Best.

**Comment by AmirMohamadBabaee** [comment]
Thanks a lot.
